# start by pulling the python image
FROM alpine:latest
RUN apk update
RUN apk add py-pip
RUN apk add --no-cache python3-dev 
RUN pip install --upgrade pip


# switch working directory
WORKDIR /app
COPY . /app
# install the dependencies and packages in the requirements file
RUN pip --no-cache-dir install -r requirements.txt
EXPOSE 5000

# copy every content from the local file to the image


# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]
CMD ["__init__.py", "__main__.py"]