# start by pulling the python image
FROM tensorflow/tensorflow:2.12.0rc0

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

# switch working directory
WORKDIR /app
COPY . /app
# install the dependencies and packages in the requirements file
RUN pip --no-cache-dir install -r requirements.txt
EXPOSE 5000

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]
CMD  ["-m", "classification_api"]